//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalGo.Publisher {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class PublisherSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PublisherSettings defaultInstance = ((PublisherSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PublisherSettings())));
        
        public static PublisherSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dotnet build")]
        public string BuildCMD {
            get {
                return ((string)(this["BuildCMD"]));
            }
            set {
                this["BuildCMD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dotnet restore")]
        public string RestoreCMD {
            get {
                return ((string)(this["RestoreCMD"]));
            }
            set {
                this["RestoreCMD"] = value;
            }
        }
    }
}
