// AUTO GENERATED
//     This code was generated by signalgo add refenreces.
//     Runtime Version : 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     to download signalgo vsix for visual studio go https://marketplace.visualstudio.com/items?itemName=AliVisualStudio.SignalGoExtension
//     support and use signalgo go https://github.com/SignalGo/SignalGo-full-net
// AUTO GENERATED
using SignalGo.Shared.DataTypes;
using System.Threading.Tasks;
using SignalGo.Shared.Models;
using SignalGo.Publisher.Shared.Models;
using ServerManagerService.Interfaces;
using ServerManagerService.ServerServices;
using ServerManagerService.HttpServices;
using ServerManagerService.ClientServices;
using System;
namespace ServerManagerService.Interfaces
{

    public partial interface IFileManagerServiceSync
    {
        global::System.Collections.Generic.List<string> GetTextFiles(global::System.Guid serviceKey);
        global::System.Collections.Generic.List<global::SignalGo.Shared.Models.HashedFileDto> CalculateFileHashes(global::System.Guid serviceKey);
    }
    public partial interface IFileManagerServiceAsync
    {
        Task<global::System.Collections.Generic.List<string>> GetTextFilesAsync(global::System.Guid serviceKey);
        Task<global::System.Collections.Generic.List<global::SignalGo.Shared.Models.HashedFileDto>> CalculateFileHashesAsync(global::System.Guid serviceKey);
    }
    [ServiceContract("filemanagerserverservice", ServiceType.ServerService, InstanceType.SingleInstance)]
    public partial interface IFileManagerService: IFileManagerServiceAsync, IFileManagerServiceSync
    {
    }
    public partial interface IServerManagerStreamServiceSync
    {
        string UploadData(global::SignalGo.Shared.Models.StreamInfo<global::SignalGo.Publisher.Shared.Models.ServiceContract> streamInfo);
        global::SignalGo.Shared.Models.StreamInfo DownloadFileData(string filePath, global::System.Guid serviceKey);
        bool SaveFileData(global::SignalGo.Shared.Models.StreamInfo<string> stream, global::System.Guid serviceKey);
        global::SignalGo.Shared.Models.StreamInfo CaptureApplicationProcess(global::System.Guid serviceKey);
    }
    public partial interface IServerManagerStreamServiceAsync
    {
        Task<string> UploadDataAsync(global::SignalGo.Shared.Models.StreamInfo<global::SignalGo.Publisher.Shared.Models.ServiceContract> streamInfo);
        Task<global::SignalGo.Shared.Models.StreamInfo> DownloadFileDataAsync(string filePath, global::System.Guid serviceKey);
        Task<bool> SaveFileDataAsync(global::SignalGo.Shared.Models.StreamInfo<string> stream, global::System.Guid serviceKey);
        Task<global::SignalGo.Shared.Models.StreamInfo> CaptureApplicationProcessAsync(global::System.Guid serviceKey);
    }
    [ServiceContract("serverstreammanagerstreamservice", ServiceType.StreamService, InstanceType.SingleInstance)]
    public partial interface IServerManagerStreamService: IServerManagerStreamServiceAsync, IServerManagerStreamServiceSync
    {
    }
    public partial interface IServerManagerServiceSync
    {
        bool StopService(global::System.Guid serviceKey);
        bool StartService(global::System.Guid serviceKey);
        bool RestartService(global::System.Guid serviceKey, bool force);
        string CallClientService(string message);
    }
    public partial interface IServerManagerServiceAsync
    {
        Task<bool> StopServiceAsync(global::System.Guid serviceKey);
        Task<bool> StartServiceAsync(global::System.Guid serviceKey);
        Task<bool> RestartServiceAsync(global::System.Guid serviceKey, bool force);
        Task<string> CallClientServiceAsync(string message);
    }
    [ServiceContract("servermanagerserverservice", ServiceType.ServerService, InstanceType.SingleInstance)]
    public partial interface IServerManagerService: IServerManagerServiceAsync, IServerManagerServiceSync
    {
    }
}

namespace ServerManagerService.ServerServices
{
    [ServiceContract("filemanagerserverservice",ServiceType.ServerService, InstanceType.SingleInstance)]
    public partial class FileManagerService : IFileManagerService
    {
        private SignalGo.Client.ClientProvider CurrentProvider { get; set; }
        string ServiceName { get; set; }
        public FileManagerService(SignalGo.Client.ClientProvider clientProvider)
        {
            CurrentProvider = clientProvider;
            ServiceName = this.GetType().GetServerServiceName(true);
        }
        public virtual global::System.Collections.Generic.List<string> GetTextFiles(global::System.Guid serviceKey)
        {
                return  SignalGo.Client.ClientManager.ConnectorExtensions.SendDataSync<global::System.Collections.Generic.List<string>>(CurrentProvider, ServiceName,"GetTextFiles", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceKey) },
                });
        }
        public virtual Task<global::System.Collections.Generic.List<string>> GetTextFilesAsync(global::System.Guid serviceKey)
        {
                return SignalGo.Client.ClientManager.ConnectorExtensions.SendDataAsync<global::System.Collections.Generic.List<string>>(CurrentProvider, ServiceName,"GetTextFiles", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceKey) },
                });
        }
        public virtual global::System.Collections.Generic.List<global::SignalGo.Shared.Models.HashedFileDto> CalculateFileHashes(global::System.Guid serviceKey)
        {
                return  SignalGo.Client.ClientManager.ConnectorExtensions.SendDataSync<global::System.Collections.Generic.List<global::SignalGo.Shared.Models.HashedFileDto>>(CurrentProvider, ServiceName,"CalculateFileHashes", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceKey) },
                });
        }
        public virtual Task<global::System.Collections.Generic.List<global::SignalGo.Shared.Models.HashedFileDto>> CalculateFileHashesAsync(global::System.Guid serviceKey)
        {
                return SignalGo.Client.ClientManager.ConnectorExtensions.SendDataAsync<global::System.Collections.Generic.List<global::SignalGo.Shared.Models.HashedFileDto>>(CurrentProvider, ServiceName,"CalculateFileHashes", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceKey) },
                });
        }
    }
    [ServiceContract("servermanagerserverservice",ServiceType.ServerService, InstanceType.SingleInstance)]
    public partial class ServerManagerService : IServerManagerService
    {
        private SignalGo.Client.ClientProvider CurrentProvider { get; set; }
        string ServiceName { get; set; }
        public ServerManagerService(SignalGo.Client.ClientProvider clientProvider)
        {
            CurrentProvider = clientProvider;
            ServiceName = this.GetType().GetServerServiceName(true);
        }
        public virtual bool StopService(global::System.Guid serviceKey)
        {
                return  SignalGo.Client.ClientManager.ConnectorExtensions.SendDataSync<bool>(CurrentProvider, ServiceName,"StopService", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceKey) },
                });
        }
        public virtual Task<bool> StopServiceAsync(global::System.Guid serviceKey)
        {
                return SignalGo.Client.ClientManager.ConnectorExtensions.SendDataAsync<bool>(CurrentProvider, ServiceName,"StopService", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceKey) },
                });
        }
        public virtual bool StartService(global::System.Guid serviceKey)
        {
                return  SignalGo.Client.ClientManager.ConnectorExtensions.SendDataSync<bool>(CurrentProvider, ServiceName,"StartService", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceKey) },
                });
        }
        public virtual Task<bool> StartServiceAsync(global::System.Guid serviceKey)
        {
                return SignalGo.Client.ClientManager.ConnectorExtensions.SendDataAsync<bool>(CurrentProvider, ServiceName,"StartService", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceKey) },
                });
        }
        public virtual bool RestartService(global::System.Guid serviceKey, bool force)
        {
                return  SignalGo.Client.ClientManager.ConnectorExtensions.SendDataSync<bool>(CurrentProvider, ServiceName,"RestartService", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceKey) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(force),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(force) },
                });
        }
        public virtual Task<bool> RestartServiceAsync(global::System.Guid serviceKey, bool force)
        {
                return SignalGo.Client.ClientManager.ConnectorExtensions.SendDataAsync<bool>(CurrentProvider, ServiceName,"RestartService", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceKey) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(force),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(force) },
                });
        }
        public virtual string CallClientService(string message)
        {
                return  SignalGo.Client.ClientManager.ConnectorExtensions.SendDataSync<string>(CurrentProvider, ServiceName,"CallClientService", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(message),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(message) },
                });
        }
        public virtual Task<string> CallClientServiceAsync(string message)
        {
                return SignalGo.Client.ClientManager.ConnectorExtensions.SendDataAsync<string>(CurrentProvider, ServiceName,"CallClientService", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(message),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(message) },
                });
        }
    }
}

namespace ServerManagerService.StreamServices
{
    [ServiceContract("serverstreammanagerstreamservice",ServiceType.StreamService, InstanceType.SingleInstance)]
    public partial class ServerManagerStreamService : IServerManagerStreamService
    {
        public string ServerAddress { get; set; }
        public int? Port { get; set; }
        private string ServiceName { get; set; }

        private SignalGo.Client.ClientProvider CurrentProvider { get; set; }
        public ServerManagerStreamService(SignalGo.Client.ClientProvider clientProvider = null)
        {
            CurrentProvider = clientProvider;
            ServiceName = GetType().GetServerServiceName(true);
        }

        public ServerManagerStreamService(string serverAddress = null, int? port = null, SignalGo.Client.ClientProvider clientProvider = null)
        {
            ServerAddress = serverAddress;
            Port = port;
            CurrentProvider = clientProvider;
            ServiceName = GetType().GetServerServiceName(true);
        }
        public virtual string UploadData(global::SignalGo.Shared.Models.StreamInfo<global::SignalGo.Publisher.Shared.Models.ServiceContract> streamInfo)
        {
                return  SignalGo.Client.ClientProvider.UploadStreamSync<string>(CurrentProvider, ServerAddress, Port, ServiceName ,"UploadData", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(streamInfo),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(streamInfo) },
                }, streamInfo);
        }
        public virtual Task<string> UploadDataAsync(global::SignalGo.Shared.Models.StreamInfo<global::SignalGo.Publisher.Shared.Models.ServiceContract> streamInfo)
        {
                return SignalGo.Client.ClientProvider.UploadStreamAsync<string>(CurrentProvider, ServerAddress, Port, ServiceName ,"UploadData", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(streamInfo),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(streamInfo) },
                }, streamInfo);
        }
        public virtual global::SignalGo.Shared.Models.StreamInfo DownloadFileData(string filePath, global::System.Guid serviceKey)
        {
                return  SignalGo.Client.ClientProvider.UploadStreamSync<global::SignalGo.Shared.Models.StreamInfo>(CurrentProvider, ServerAddress, Port, ServiceName ,"DownloadFileData", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(filePath),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(filePath) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceKey) },
                }, null);
        }
        public virtual Task<global::SignalGo.Shared.Models.StreamInfo> DownloadFileDataAsync(string filePath, global::System.Guid serviceKey)
        {
                return SignalGo.Client.ClientProvider.UploadStreamAsync<global::SignalGo.Shared.Models.StreamInfo>(CurrentProvider, ServerAddress, Port, ServiceName ,"DownloadFileData", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(filePath),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(filePath) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceKey) },
                }, null);
        }
        public virtual bool SaveFileData(global::SignalGo.Shared.Models.StreamInfo<string> stream, global::System.Guid serviceKey)
        {
                return  SignalGo.Client.ClientProvider.UploadStreamSync<bool>(CurrentProvider, ServerAddress, Port, ServiceName ,"SaveFileData", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(stream),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(stream) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceKey) },
                }, stream);
        }
        public virtual Task<bool> SaveFileDataAsync(global::SignalGo.Shared.Models.StreamInfo<string> stream, global::System.Guid serviceKey)
        {
                return SignalGo.Client.ClientProvider.UploadStreamAsync<bool>(CurrentProvider, ServerAddress, Port, ServiceName ,"SaveFileData", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(stream),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(stream) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceKey) },
                }, stream);
        }
        public virtual global::SignalGo.Shared.Models.StreamInfo CaptureApplicationProcess(global::System.Guid serviceKey)
        {
                return  SignalGo.Client.ClientProvider.UploadStreamSync<global::SignalGo.Shared.Models.StreamInfo>(CurrentProvider, ServerAddress, Port, ServiceName ,"CaptureApplicationProcess", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceKey) },
                }, null);
        }
        public virtual Task<global::SignalGo.Shared.Models.StreamInfo> CaptureApplicationProcessAsync(global::System.Guid serviceKey)
        {
                return SignalGo.Client.ClientProvider.UploadStreamAsync<global::SignalGo.Shared.Models.StreamInfo>(CurrentProvider, ServerAddress, Port, ServiceName ,"CaptureApplicationProcess", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceKey) },
                }, null);
        }
    }
}

namespace ServerManagerService.OneWayServices
{
}

namespace ServerManagerService.HttpServices
{
    public partial class FileManagerService : IFileManagerService
    {
        public FileManagerService(string serverUrl, SignalGo.Client.IHttpClient httpClient = null)
        {
            _serverUrl = serverUrl;
            _httpClient = httpClient;
            if (_httpClient == null)
                _httpClient = new SignalGo.Client.HttpClient();
        }

        private readonly string _serverUrl = null;
        private SignalGo.Client.IHttpClient _httpClient;
        public SignalGo.Shared.Http.WebHeaderCollection RequestHeaders
        {
            get
            {
                return _httpClient.RequestHeaders;
            }
            set
            {
                _httpClient.RequestHeaders = value;
            }
        }

        public SignalGo.Shared.Http.WebHeaderCollection ResponseHeaders { get; set; }
        public System.Net.HttpStatusCode Status { get; set; }
        public static FileManagerService Current { get; set; }
        public virtual global::System.Collections.Generic.List<string> GetTextFiles(global::System.Guid serviceKey)
        {
                SignalGo.Client.HttpClientResponse result = _httpClient.Post(_serverUrl + (_serverUrl.EndsWith("/") ? "" : "/") + "filemanager/GetTextFiles", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceKey) },
                });
                ResponseHeaders = result.ResponseHeaders;
                Status = result.Status;
                if (Status == System.Net.HttpStatusCode.InternalServerError)
                        throw new Exception(result.Data);
                return _httpClient.Deserialize<global::System.Collections.Generic.List<string>>(result.Data);
        }
        public virtual async Task<global::System.Collections.Generic.List<string>> GetTextFilesAsync(global::System.Guid serviceKey)
        {
                SignalGo.Client.HttpClientResponse result = await _httpClient.PostAsync(_serverUrl + (_serverUrl.EndsWith("/") ? "" : "/") + "filemanager/GetTextFiles", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceKey) },
                });
                ResponseHeaders = result.ResponseHeaders;
                Status = result.Status;
                if (Status == System.Net.HttpStatusCode.InternalServerError)
                        throw new Exception(result.Data);
                return _httpClient.Deserialize<global::System.Collections.Generic.List<string>>(result.Data);
        }
        public virtual global::System.Collections.Generic.List<global::SignalGo.Shared.Models.HashedFileDto> CalculateFileHashes(global::System.Guid serviceKey)
        {
                SignalGo.Client.HttpClientResponse result = _httpClient.Post(_serverUrl + (_serverUrl.EndsWith("/") ? "" : "/") + "filemanager/CalculateFileHashes", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceKey) },
                });
                ResponseHeaders = result.ResponseHeaders;
                Status = result.Status;
                if (Status == System.Net.HttpStatusCode.InternalServerError)
                        throw new Exception(result.Data);
                return _httpClient.Deserialize<global::System.Collections.Generic.List<global::SignalGo.Shared.Models.HashedFileDto>>(result.Data);
        }
        public virtual async Task<global::System.Collections.Generic.List<global::SignalGo.Shared.Models.HashedFileDto>> CalculateFileHashesAsync(global::System.Guid serviceKey)
        {
                SignalGo.Client.HttpClientResponse result = await _httpClient.PostAsync(_serverUrl + (_serverUrl.EndsWith("/") ? "" : "/") + "filemanager/CalculateFileHashes", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceKey) },
                });
                ResponseHeaders = result.ResponseHeaders;
                Status = result.Status;
                if (Status == System.Net.HttpStatusCode.InternalServerError)
                        throw new Exception(result.Data);
                return _httpClient.Deserialize<global::System.Collections.Generic.List<global::SignalGo.Shared.Models.HashedFileDto>>(result.Data);
        }
    }
}

namespace ServerManagerService.ClientServices
{
}

