// AUTO GENERATED
//     This code was generated by signalgo add refenreces.
//     Runtime Version : 4.6.3.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     to download signalgo vsix for visual studio go https://marketplace.visualstudio.com/items?itemName=AliVisualStudio.SignalGoExtension
//     support and use signalgo go https://github.com/SignalGo/SignalGo-full-net
// AUTO GENERATED
using SignalGo.Shared.DataTypes;
using System.Threading.Tasks;
using SignalGo.Shared.Models;
using ServerManagerService.Interfaces;
using ServerManagerService.ServerServices;
using ServerManagerService.HttpServices;
using ServerManagerService.ClientServices;
using System;
namespace ServerManagerService.Interfaces
{

    [ServiceContract("servermanagerserverservice", ServiceType.ServerService, InstanceType.SingleInstance)]
    public partial interface IServerManagerService
    {
        bool StopServer(System.Guid serverKey, string name);
        Task<bool> StopServerAsync(System.Guid serverKey, string name);
        bool StopServer(System.Guid serverKey);
        Task<bool> StopServerAsync(System.Guid serverKey);
        bool StartServer(System.Guid serverKey, string name);
        Task<bool> StartServerAsync(System.Guid serverKey, string name);
        bool StartServer(System.Guid serverKey);
        Task<bool> StartServerAsync(System.Guid serverKey);
        bool RestartServer(System.Guid serverKey, string name, bool force);
        Task<bool> RestartServerAsync(System.Guid serverKey, string name, bool force);
        bool RestartServer(System.Guid serverKey, bool force);
        Task<bool> RestartServerAsync(System.Guid serverKey, bool force);
        string CallClientService(string message);
        Task<string> CallClientServiceAsync(string message);
        string SayHello(string name);
        Task<string> SayHelloAsync(string name);
    }
    [ServiceContract("serverstreammanagerstreamservice", ServiceType.StreamService, InstanceType.SingleInstance)]
    public partial interface IServerManagerStreamService
    {
        string UploadData(SignalGo.Shared.Models.StreamInfo streamInfo, SignalGo.Shared.Models.ServiceContract serviceContract);
        Task<string> UploadDataAsync(SignalGo.Shared.Models.StreamInfo streamInfo, SignalGo.Shared.Models.ServiceContract serviceContract);
        void DisposeStream();
        Task DisposeStreamAsync();
        void DeCompress(string archive, SignalGo.Shared.Models.ServiceContract serviceContract, SignalGo.ServerManager.Models.CompressionMethodType compressionMethod);
        Task DeCompressAsync(string archive, SignalGo.Shared.Models.ServiceContract serviceContract, SignalGo.ServerManager.Models.CompressionMethodType compressionMethod);
    }
}

namespace ServerManagerService.ServerServices
{
    [ServiceContract("servermanagerserverservice",ServiceType.ServerService, InstanceType.SingleInstance)]
    public partial class ServerManagerService : IServerManagerService
    {
        private SignalGo.Client.ClientProvider CurrentProvider { get; set; }
        string ServiceName { get; set; }
        public ServerManagerService(SignalGo.Client.ClientProvider clientProvider)
        {
            CurrentProvider = clientProvider;
            ServiceName = this.GetType().GetServerServiceName(true);
        }
        public bool StopServer(System.Guid serverKey, string name)
        {
                return  SignalGo.Client.ClientManager.ConnectorExtensions.SendDataSync<bool>(CurrentProvider, ServiceName,"StopServer", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serverKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serverKey) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(name),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(name) },
                });
        }
        public Task<bool> StopServerAsync(System.Guid serverKey, string name)
        {
                return SignalGo.Client.ClientManager.ConnectorExtensions.SendDataAsync<bool>(CurrentProvider, ServiceName,"StopServer", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serverKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serverKey) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(name),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(name) },
                });
        }
        public bool StopServer(System.Guid serverKey)
        {
                return  SignalGo.Client.ClientManager.ConnectorExtensions.SendDataSync<bool>(CurrentProvider, ServiceName,"StopServer", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serverKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serverKey) },
                });
        }
        public Task<bool> StopServerAsync(System.Guid serverKey)
        {
                return SignalGo.Client.ClientManager.ConnectorExtensions.SendDataAsync<bool>(CurrentProvider, ServiceName,"StopServer", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serverKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serverKey) },
                });
        }
        public bool StartServer(System.Guid serverKey, string name)
        {
                return  SignalGo.Client.ClientManager.ConnectorExtensions.SendDataSync<bool>(CurrentProvider, ServiceName,"StartServer", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serverKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serverKey) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(name),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(name) },
                });
        }
        public Task<bool> StartServerAsync(System.Guid serverKey, string name)
        {
                return SignalGo.Client.ClientManager.ConnectorExtensions.SendDataAsync<bool>(CurrentProvider, ServiceName,"StartServer", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serverKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serverKey) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(name),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(name) },
                });
        }
        public bool StartServer(System.Guid serverKey)
        {
                return  SignalGo.Client.ClientManager.ConnectorExtensions.SendDataSync<bool>(CurrentProvider, ServiceName,"StartServer", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serverKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serverKey) },
                });
        }
        public Task<bool> StartServerAsync(System.Guid serverKey)
        {
                return SignalGo.Client.ClientManager.ConnectorExtensions.SendDataAsync<bool>(CurrentProvider, ServiceName,"StartServer", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serverKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serverKey) },
                });
        }
        public bool RestartServer(System.Guid serverKey, string name, bool force)
        {
                return  SignalGo.Client.ClientManager.ConnectorExtensions.SendDataSync<bool>(CurrentProvider, ServiceName,"RestartServer", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serverKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serverKey) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(name),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(name) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(force),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(force) },
                });
        }
        public Task<bool> RestartServerAsync(System.Guid serverKey, string name, bool force)
        {
                return SignalGo.Client.ClientManager.ConnectorExtensions.SendDataAsync<bool>(CurrentProvider, ServiceName,"RestartServer", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serverKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serverKey) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(name),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(name) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(force),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(force) },
                });
        }
        public bool RestartServer(System.Guid serverKey, bool force)
        {
                return  SignalGo.Client.ClientManager.ConnectorExtensions.SendDataSync<bool>(CurrentProvider, ServiceName,"RestartServer", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serverKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serverKey) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(force),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(force) },
                });
        }
        public Task<bool> RestartServerAsync(System.Guid serverKey, bool force)
        {
                return SignalGo.Client.ClientManager.ConnectorExtensions.SendDataAsync<bool>(CurrentProvider, ServiceName,"RestartServer", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serverKey),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serverKey) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(force),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(force) },
                });
        }
        public string CallClientService(string message)
        {
                return  SignalGo.Client.ClientManager.ConnectorExtensions.SendDataSync<string>(CurrentProvider, ServiceName,"CallClientService", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(message),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(message) },
                });
        }
        public Task<string> CallClientServiceAsync(string message)
        {
                return SignalGo.Client.ClientManager.ConnectorExtensions.SendDataAsync<string>(CurrentProvider, ServiceName,"CallClientService", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(message),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(message) },
                });
        }
        public string SayHello(string name)
        {
                return  SignalGo.Client.ClientManager.ConnectorExtensions.SendDataSync<string>(CurrentProvider, ServiceName,"SayHello", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(name),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(name) },
                });
        }
        public Task<string> SayHelloAsync(string name)
        {
                return SignalGo.Client.ClientManager.ConnectorExtensions.SendDataAsync<string>(CurrentProvider, ServiceName,"SayHello", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(name),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(name) },
                });
        }
    }
}

namespace ServerManagerService.StreamServices
{
    [ServiceContract("serverstreammanagerstreamservice",ServiceType.StreamService, InstanceType.SingleInstance)]
    public partial class ServerManagerStreamService : IServerManagerStreamService
    {
        public string ServerAddress { get; set; }
        public int? Port { get; set; }
        private string ServiceName { get; set; }

        private SignalGo.Client.ClientProvider CurrentProvider { get; set; }
        public ServerManagerStreamService(SignalGo.Client.ClientProvider clientProvider = null)
        {
            CurrentProvider = clientProvider;
            ServiceName = GetType().GetServerServiceName(true);
        }

        public ServerManagerStreamService(string serverAddress = null, int? port = null, SignalGo.Client.ClientProvider clientProvider = null)
        {
            ServerAddress = serverAddress;
            Port = port;
            CurrentProvider = clientProvider;
            ServiceName = GetType().GetServerServiceName(true);
        }
        public string UploadData(SignalGo.Shared.Models.StreamInfo streamInfo, SignalGo.Shared.Models.ServiceContract serviceContract)
        {
                return  SignalGo.Client.ClientProvider.UploadStreamSync<string>(CurrentProvider, ServerAddress, Port, ServiceName ,"UploadData", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(streamInfo),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(streamInfo) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceContract),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceContract) },
                }, streamInfo);
        }
        public Task<string> UploadDataAsync(SignalGo.Shared.Models.StreamInfo streamInfo, SignalGo.Shared.Models.ServiceContract serviceContract)
        {
                return SignalGo.Client.ClientProvider.UploadStreamAsync<string>(CurrentProvider, ServerAddress, Port, ServiceName ,"UploadData", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(streamInfo),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(streamInfo) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceContract),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceContract) },
                }, streamInfo);
        }
        public void DisposeStream()
        {
                 SignalGo.Client.ClientProvider.UploadStreamSync<object>(CurrentProvider, ServerAddress, Port, ServiceName ,"DisposeStream", new SignalGo.Shared.Models.ParameterInfo[]
                {
                }, null);
        }
        public Task DisposeStreamAsync()
        {
                return SignalGo.Client.ClientProvider.UploadStreamAsync<object>(CurrentProvider, ServerAddress, Port, ServiceName ,"DisposeStream", new SignalGo.Shared.Models.ParameterInfo[]
                {
                }, null);
        }
        public void DeCompress(string archive, SignalGo.Shared.Models.ServiceContract serviceContract, SignalGo.ServerManager.Models.CompressionMethodType compressionMethod)
        {
                 SignalGo.Client.ClientProvider.UploadStreamSync<object>(CurrentProvider, ServerAddress, Port, ServiceName ,"DeCompress", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(archive),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(archive) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceContract),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceContract) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(compressionMethod),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(compressionMethod) },
                }, null);
        }
        public Task DeCompressAsync(string archive, SignalGo.Shared.Models.ServiceContract serviceContract, SignalGo.ServerManager.Models.CompressionMethodType compressionMethod)
        {
                return SignalGo.Client.ClientProvider.UploadStreamAsync<object>(CurrentProvider, ServerAddress, Port, ServiceName ,"DeCompress", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(archive),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(archive) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceContract),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceContract) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(compressionMethod),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(compressionMethod) },
                }, null);
        }
    }
}

namespace ServerManagerService.OneWayServices
{
}

namespace ServerManagerService.HttpServices
{
    public partial class ServerManagerStreamService : IServerManagerStreamService
    {
        public ServerManagerStreamService(string serverUrl, SignalGo.Client.IHttpClient httpClient = null)
        {
            _serverUrl = serverUrl;
            _httpClient = httpClient;
            if (_httpClient == null)
                _httpClient = new SignalGo.Client.HttpClient();
        }

        private readonly string _serverUrl = null;
        private SignalGo.Client.IHttpClient _httpClient;
        public SignalGo.Shared.Http.WebHeaderCollection RequestHeaders
        {
            get
            {
                return _httpClient.RequestHeaders;
            }
            set
            {
                _httpClient.RequestHeaders = value;
            }
        }

        public SignalGo.Shared.Http.WebHeaderCollection ResponseHeaders { get; set; }
        public System.Net.HttpStatusCode Status { get; set; }
        public static ServerManagerStreamService Current { get; set; }
        public string UploadData(SignalGo.Shared.Models.StreamInfo streamInfo, SignalGo.Shared.Models.ServiceContract serviceContract)
        {
                SignalGo.Client.HttpClientResponse result = _httpClient.Post(_serverUrl + (_serverUrl.EndsWith("/") ? "" : "/") + "serverstreammanager/UploadData", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(streamInfo),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(streamInfo) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceContract),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceContract) },
                }, streamInfo);
                ResponseHeaders = result.ResponseHeaders;
                Status = result.Status;
                if (Status == System.Net.HttpStatusCode.InternalServerError)
                        throw new Exception(result.Data);
                return _httpClient.Deserialize<string>(result.Data);
        }
        public async Task<string> UploadDataAsync(SignalGo.Shared.Models.StreamInfo streamInfo, SignalGo.Shared.Models.ServiceContract serviceContract)
        {
                SignalGo.Client.HttpClientResponse result = await _httpClient.PostAsync(_serverUrl + (_serverUrl.EndsWith("/") ? "" : "/") + "serverstreammanager/UploadData", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(streamInfo),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(streamInfo) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceContract),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceContract) },
                }, streamInfo);
                ResponseHeaders = result.ResponseHeaders;
                Status = result.Status;
                if (Status == System.Net.HttpStatusCode.InternalServerError)
                        throw new Exception(result.Data);
                return _httpClient.Deserialize<string>(result.Data);
        }
        public void DisposeStream()
        {
                SignalGo.Client.HttpClientResponse result = _httpClient.Post(_serverUrl + (_serverUrl.EndsWith("/") ? "" : "/") + "serverstreammanager/DisposeStream", new SignalGo.Shared.Models.ParameterInfo[]
                {
                });
                ResponseHeaders = result.ResponseHeaders;
                Status = result.Status;
                if (Status == System.Net.HttpStatusCode.InternalServerError)
                        throw new Exception(result.Data);
        }
        public async Task DisposeStreamAsync()
        {
                SignalGo.Client.HttpClientResponse result = await _httpClient.PostAsync(_serverUrl + (_serverUrl.EndsWith("/") ? "" : "/") + "serverstreammanager/DisposeStream", new SignalGo.Shared.Models.ParameterInfo[]
                {
                });
                ResponseHeaders = result.ResponseHeaders;
                Status = result.Status;
                if (Status == System.Net.HttpStatusCode.InternalServerError)
                        throw new Exception(result.Data);
        }
        public void DeCompress(string archive, SignalGo.Shared.Models.ServiceContract serviceContract, SignalGo.ServerManager.Models.CompressionMethodType compressionMethod)
        {
                SignalGo.Client.HttpClientResponse result = _httpClient.Post(_serverUrl + (_serverUrl.EndsWith("/") ? "" : "/") + "serverstreammanager/DeCompress", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(archive),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(archive) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceContract),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceContract) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(compressionMethod),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(compressionMethod) },
                });
                ResponseHeaders = result.ResponseHeaders;
                Status = result.Status;
                if (Status == System.Net.HttpStatusCode.InternalServerError)
                        throw new Exception(result.Data);
        }
        public async Task DeCompressAsync(string archive, SignalGo.Shared.Models.ServiceContract serviceContract, SignalGo.ServerManager.Models.CompressionMethodType compressionMethod)
        {
                SignalGo.Client.HttpClientResponse result = await _httpClient.PostAsync(_serverUrl + (_serverUrl.EndsWith("/") ? "" : "/") + "serverstreammanager/DeCompress", new SignalGo.Shared.Models.ParameterInfo[]
                {
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(archive),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(archive) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(serviceContract),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(serviceContract) },
                         new  SignalGo.Shared.Models.ParameterInfo() { Name = nameof(compressionMethod),Value = SignalGo.Client.ClientSerializationHelper.SerializeObject(compressionMethod) },
                });
                ResponseHeaders = result.ResponseHeaders;
                Status = result.Status;
                if (Status == System.Net.HttpStatusCode.InternalServerError)
                        throw new Exception(result.Data);
        }
    }
}

namespace ServerManagerService.ClientServices
{
}

namespace SignalGo.ServerManager.Models
{
    public enum CompressionMethodType : int
    {
        None = 0,
        Zip = 1,
        Gzip = 2,
        Rar = 3,
        Tar = 4,
        bzip = 5,
        Zip7 = 6,
    }

}

